name: Scoreboard-OG
author: NotAlexNoyle
description: A simple Scoreboard plugin with MiniPlaceholder API support.
website: https://github.com/true-og/Scoreboard-OG/
version: '${version}'
api-version: '${apiVersion}'
main: plugin.ScoreboardOG
depend: 
  - DiamondBank-OG
  - Utilities-OG
  - PacketEvents-OG
  - LuckPerms
softdepend:
  - ProtocolLib
  - ViaVersion
  - ViaBackwards
  - ViaRewind
