name: Scoreboard-OG
author: NotAlexNoyle
description: A simple Scoreboard plugin with MiniPlaceholder API support.
website: https://github.com/true-og/Scoreboard-OG/
version: '${version}'
api-version: '${apiVersion}'
main: plugin.ScoreboardOG
depend: 
  - DiamondBank-OG
  - Utilities-OG
  - LuckPerms
  - ViaVersion
  - ViaBackwards
  - ViaRewind
softdepend:
  - PlaceholderAPI
  - ProtocolLib
commands:
  togglescoreboard:
    description: Toggle the sidebar scoreboard on or off.
    usage: /togglescoreboard
    permission: scoreboard.toggle
permissions:
  scoreboard.toggle:
    description: Allows a player to toggle their scoreboard visibility.
    default: true
